export const USER_ACTION_TYPES = {
	SET_CURRENT_USER: 'user/SET_CURRENT_USER',
	CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
	SIGN_IN_WITH_EMAIL_AND_PASSWORD: 'user/SIGN_IN_WITH_EMAIL_AND_PASSWORD',
	SIGN_OUT: 'user/SIGN_OUT',
	SIGN_UP: 'user/SIGN_UP',
	GOOGLE_SIGN_IN: 'user/GOOGLE_SIGN_IN',
	SIGN_IN_SUCCESS: 'user/SIGN_IN_SUCCESS',
	SIGN_IN_FAILURE: 'user/SIGN_IN_FAILURE',
};
